# Matrizen in python (bzw. in numpy)


In [175]:
import numpy as np

Vektoren und Matrizen sind **numpy arrays**. Im Gegensatz zu anderen Aufzählungen (listen) enthalten Sie nur einen einzigen (numerischen) Datentyp. Dafür unterstützen sie diverse Matrix- und Vektoroperationen

In [211]:
b = np.array([3,-1,2,4,-5.])
print("Beispiel für Vektor", b)

A = np.random.randint(low = 2, high = 8, size = (5,5) ) # ganzzahlige Zufallsmatrix
print("\nZufällige 3 x 3 Matrix \n", A, "\n")

c = np.zeros_like(b) # Nullen der gleichen Form wie b. Funktioniert auch für Matrizen
print("c = ", c)

M = np.zeros( shape = (3, 4)) # alternativ: direkte Angabe der gewünschten Dimensionen
print("\nNullmatrix \n", M, "\n")

I = np.arange(start = 3, stop = 10) # "Zählvektor" oder Indexvektor. In vielem ähnlich wie das builtin range
print("range: ", I)

Beispiel für Vektor [ 3. -1.  2.  4. -5.]

Zufällige 3 x 3 Matrix 
 [[6 3 2 4 4]
 [7 5 4 2 5]
 [3 7 3 3 7]
 [2 7 3 4 2]
 [4 7 6 2 7]] 

c =  [0. 0. 0. 0. 0.]

Nullmatrix 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

range:  [3 4 5 6 7 8 9]


### Elementare Operationen mit Matrizen und Vektoren 
Für **Matrixprodukte** gibt es den Operator @. Der Stern "*" arbeitet elementweise. Daneben gibt es Matrix- und Vektornormen, Transposition etc.

In [202]:
print("b = ", b, "\n\n")
print("A * b = ", A @ b)
print("Skalarprodukt von b mit sich selber = ", b @ b) # python unterscheidet nicht zwischen Zeilen- und Spaltenvektoren!
print("punktweises Produkt von b mit sich selber = ", b * b)
print("Transposition: A^T = \n", A.T)
print("Addition: b - 3 * b", b - 3 * b)
print("Addition einer Konstanten ", b - 7)
print("Summe aller Elemente von b: ", np.sum(b))
print("Produkt aller Elemente von b: ", np.prod(b))
print("Maximales Element von b: ", np.max(b))
print("Index, der zu dem Max gehört: ", np.argmax(b))
print("Vektornorm von b: ", np.linalg.norm(b))

b =  [ 3. -1.  2.  4. -5.] 


A * b =  [17. 11. 12.  0. 23.]
Skalarprodukt von b mit sich selber =  55.0
punktweises Produkt von b mit sich selber =  [ 9.  1.  4. 16. 25.]
Transposition: A^T = 
 [[7 3 6 2 7]
 [6 3 6 6 5]
 [2 6 6 5 2]
 [2 2 2 5 7]
 [2 3 4 6 5]]
Addition: b - 3 * b [-6.  2. -4. -8. 10.]
Addition einer Konstanten  [ -4.  -8.  -5.  -3. -12.]
Summe aller Elemente von b:  3.0
Produkt aller Elemente von b:  120.0
Maximales Element von b:  4.0
Index, der zu dem Max gehört:  3
Vektornorm von b:  7.416198487095663


### Indices
Alle Indices in python starten bei 0. Es kann auch auf ganze Bereiche zugegriffen werden. Obere Grenzen sind exklusive

In [178]:
print("b = ", b) 
i = 2
print("Element ", i, " von b: ", b[i])
o = 3
print("Elemente bis ", o, " von b: ", b[:o])
u = 1
print("Elemente von ", u, " bis ", o, " von b: ", b[u:o])
print("Alle Elemente von ", u, " von b: ", b[u:])

b =  [ 3. -1.  2.  4. -5.]
Element  2  von b:  2.0
Elemente bis  3  von b:  [ 3. -1.  2.]
Elemente von  1  bis  3  von b:  [-1.  2.]
Alle Elemente von  1  von b:  [-1.  2.  4. -5.]


**Negative Indices** zählen vom Ende her. b[-1] gibt das letzte Element von b

In [179]:
i = -3
print("b[", i, "] = ", b[i])

b[ -3 ] =  2.0


**Analoges gilt für Matrizen**

In [194]:
print("A = \n", A,"\n\n")
i, j = 3, 2
print("A[",i,",",j,"] = ", A[i, j], "\n")
print("Alle Elemente der Spalte ", j, " von A:", A[:,j], "\n")
print("Submatrix A[",i,":,",j,":] = \n", A[i:, j:], "\n")
print("Alle Elemente der Spalte ", i, " ab Zeile ", j, ": ", A[j:, i])

A = 
 [[6 4 7 4 6]
 [2 4 4 3 3]
 [5 2 7 6 6]
 [4 4 7 3 4]
 [5 6 7 4 6]] 


A[ 3 , 2 ] =  7 

Alle Elemente der Spalte  2  von A: [7 4 7 7 7] 

Submatrix A[ 3 :, 2 :] = 
 [[7 3 4]
 [7 4 6]] 

Alle Elemente der Spalte  3  ab Zeile  2 :  [6 3 4]


**Diagonale und für untere und obere Dreiecksmatrizen**

In [181]:
print("A = \n", A, "\n")
print("Hauptdiagonale von A", np.diag(A))
i = -1
print("Untere Dreiecksmatrix von A\n", np.tril(A, i)) #analog triu für obere Dreiecksmatrizen

A = 
 [[4 4 7 3 4]
 [2 4 4 3 3]
 [5 2 7 6 6]
 [6 4 7 4 6]
 [5 6 7 4 6]] 

Hauptdiagonale von A [4 4 7 4 6]
Untere Dreiecksmatrix von A
 [[0 0 0 0 0]
 [2 0 0 0 0]
 [5 2 0 0 0]
 [6 4 7 0 0]
 [5 6 7 4 0]]


**Die Einheitsmatrix**

In [182]:
print("Einheitsmatrix \n", np.eye(5))

Einheitsmatrix 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Aus A die untere Dreiecksmatrix ohne Hauptdiagonale extrahieren und eine Einheitsmatrix addieren:

In [183]:
np.tril(A,-1) + np.eye(5)

array([[1., 0., 0., 0., 0.],
       [2., 1., 0., 0., 0.],
       [5., 2., 1., 0., 0.],
       [6., 4., 7., 1., 0.],
       [5., 6., 7., 4., 1.]])

**Zeilen einer Matrix vertauschen**
Zeilen einer Matrix können auch in der Form
$$
    A[i]
$$
angesprochen werden, d.h. eine Matrix ist (wie in C) ein array von Vektoren, auch möglich ist z.B.
$$
    I = [1, 3, 2], \quad A[I]   
$$

oder direkt

$$
    A[[1, 3, 2]]
$$

In [184]:
print("A = \n", A, "\n")
i, j = 0, 3
print("Zeilen ", i, " und ", j, " von A:\n ", A[[i, j]], "\n")
print("Zeilen ", i, " und ", j, " von A vertauschen")
A[[i, j]] = A[[j, i]]
print("A = \n", A, "\n")

A = 
 [[4 4 7 3 4]
 [2 4 4 3 3]
 [5 2 7 6 6]
 [6 4 7 4 6]
 [5 6 7 4 6]] 

Zeilen  0  und  3  von A:
  [[4 4 7 3 4]
 [6 4 7 4 6]] 

Zeilen  0  und  3  von A vertauschen
A = 
 [[6 4 7 4 6]
 [2 4 4 3 3]
 [5 2 7 6 6]
 [4 4 7 3 4]
 [5 6 7 4 6]] 



Für Arrays werden bei Übergabe an Funktionen oder durch "=" nur die Referenzen übergeben bzw. gleichgesetzt.
$$
    B  = A
$$

bedeutet, dass B auf die Daten von A zugreift. Wenn man eine Kopie möchte, geht das mit

$$
    B = A.copy()
$$

In [185]:
print("b = ", b) 
v = b.copy()                     # v = b oder v = b.copy() verhalten sich unterschiedlich
print("v = ", v)
v[0] = -v[0]
print("b = ", b, "  v = ", v)

b =  [ 3. -1.  2.  4. -5.]
v =  [ 3. -1.  2.  4. -5.]
b =  [ 3. -1.  2.  4. -5.]   v =  [-3. -1.  2.  4. -5.]


Das entsprechende gilt für Übergabe an Funktionen (_call by reference_)

In [186]:
def f(M):
    M *= 2

v = np.array([1,2,3])
print("v = ", v)
f(v)
print("v = ", v)

v =  [1 2 3]
v =  [2 4 6]


Wenn man die ursprüngliche Matrix behalten will, muss man beim Aufruf oder in der Funktion eine Kopie erstellen

In [187]:
def f(M0):
    M = M0.copy() # Daten kopieren
    M *= 2

v = np.array([1,2,3])
print("v = ", v)
f(v)
print("v = ", v)

v =  [1 2 3]
v =  [1 2 3]


Logische Operatoren und logisches Indexing geht auch:

In [208]:
u = 3 
print("A > ", u, "\n", A > u, "\n")
print("A > ", u, ":\n", 1 * (A > u), "\n")
print("alle Elemente von A, die > ", u, " sind:", A[A>3])
print("Alles <= ", u, " auf Null setzen: \n", A * (A > u)) # "*" wirkt elementweise!

A >  3 
 [[ True  True False False False]
 [False False  True False False]
 [ True  True  True False  True]
 [False  True  True  True  True]
 [ True  True False  True  True]] 

A >  3 :
 [[1 1 0 0 0]
 [0 0 1 0 0]
 [1 1 1 0 1]
 [0 1 1 1 1]
 [1 1 0 1 1]] 

alle Elemente von A, die >  3  sind: [7 6 6 6 6 6 4 6 5 5 6 7 5 7 5]
Alles <=  3  auf Null setzen: 
 [[7 6 0 0 0]
 [0 0 6 0 0]
 [6 6 6 0 4]
 [0 6 5 5 6]
 [7 5 0 7 5]]


### List comprehension
python bietet praktische Shortcuts zur Erstellung von Listen an. 

In [213]:
# Gegendiagonale der Matrix A, d.h. alle Elemente der Form A[i, n-i]
print("A = \n", A, "\n")
n = A.shape[0]
d = [A[i, -(i+1)] for i in range(n)] # i = 0: [0,-1], i = 1: [1, -2], etc.
print("Gegendiagonale: ", d)
print("... in umgekehrter Reihenfolge: ", np.flip(d))
print("z. B. die Summe aller Elemente der Gegendiagonalen", np.sum([A[i, -(i+1)] for i in range(n)]))


A = 
 [[6 3 2 4 4]
 [7 5 4 2 5]
 [3 7 3 3 7]
 [2 7 3 4 2]
 [4 7 6 2 7]] 

Gegendiagonale:  [4, 2, 3, 7, 4]
... in umgekehrter Reihenfolge:  [4 7 3 2 4]
z. B. die Summe aller Elemente der Gegendiagonalen 20
